### PR TITLE
Readme: simplify installation

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by Mikulas** [comment]
Hi, sorry, I'll not merge this. I believe locking dependencies (including dev tools) to major version is correct.

**Comment by TomasVotruba** [comment]
Hi, then we agree on the same thing. What do you think this would cause?

The most recent mayor version is picked by default by composer. If you release version `5.0`, it will be locked in composer to `^5.0`. With no need to change the readme - that's the goal of this PR.

**Comment by Mikulas** [comment]
Fair enough. It's not the same as it limits the minor version (it would lock to ~4.2 instead of ~4.0) but I don't really care that much.

**Comment by Mikulas** [comment]
Thank you :)

Btw I've noticed adminer builds are no longer on sourceforge and most recent tags are broken :/

**Comment by TomasVotruba** [comment]
I send this PR because many packages have outdated README. The have e.g. v2 in it and there is already v4 released. DRY.

I download adminer manually, so not really know how to help.
I see Adminer is on Github: https://github.com/vrana/adminer, yet in dew

**Pull request merged**
